### ISSUE TITLE
Get_token errors when running HASSIO on RPi

### ISSUE THREAD

**Issue by tubes41** [sermayoral/ha-samsungtv-encrypted#12]
#5 is unresolved.
Unable to use a HassOS terminal to run get_token.py due to compatibility issues on the latest HassOS builds.
Below is the error shown when get_token.py imports pycryptodome.
![image](https://user-images.githubusercontent.com/2478421/77678519-403d6b80-6fcc-11ea-8967-e1c10670ac8c.png)

Python: 3.8
HomeAssistant: 0.107.1
HassOS: 3.12

manifest.json should list all dependencies (including pycryptodome, requests, websockets, etc). This should resolve the issue?

**Comment by sermayoral** [comment]
@tubes41 I'm not sure because Hass.io is very close. Can you try it, but i don't thing it is a good idea. Its a script that you are going to execute once. Install all them in Hass.io, in my opinion, has no sense.

I think doing an executable in order to make easy to all user execute it is the best solution to this problem. I have to think a little more about it

**Comment by skky88** [comment]
HI @tubes41, I can report my situation:
I successfully execute the get_token.py command directly from HASSIO terminal, but my installation is little bit strange:
I have a server (an HP microserver gen.8 with xenon CPU and 8GB of ram), that running a Synology DSM image, on this image I have the docker application that running all HASS container.
I bypass your same problem by running all command directly in the terminal command line of docker in the Homeassistant container (Hassio platform running various container, the main one is HOMEASSISTANT).
Inside homeassistant command line I install all necessary dependencies (most off them was already installed), than I change the folder:
**_CD /config/custom_components/samsungtv_encrypted_**
than i run the get_token.py
**_python get_token.py --ip (your IP) --port 8080_**
Like this I obtain the token for two of my TVs.
I think that main problem on HASSIO is that this config of HASS running on virtual docker solution,  and in order to properly run all command you need to run the shell command on HOMEASSISTANT container and not on HASSIO main home.

**Comment by sermayoral** [comment]
@skky88 thanks

@tubes41 does it works for you?
