### ISSUE TITLE
Elaborate on the difference between v2 and v2-hdmi in README.md

### ISSUE THREAD

**Issue by GuyKh** [sermayoral/ha-samsungtv-encrypted#3]
Thanks for the awesome work.

Could you add an explanation when to use which version?

In my case - I have my TV connected to a reciever which the HomeAssistant (on RaspberryPi) is connected to, and a streamer and other media players.

Which should I use?
I think it's also better to have this explanation in `Readme.md` to avoid ambiguity in this regard

Thanks

**Comment by sermayoral** [comment]
@GuyKh, as you know, the POWER_ON button does not work with encrypted TVs.

If you have your Home Assistant server connected to the TV by HDMI, and your Home Assistant configured so that you can call this service to turn on the TV:
```
service: hdmi_cec.power_on
```
So, you can use the *-hdmi version and getting full control over your TV.

More info in: https://www.home-assistant.io/integrations/hdmi_cec/

Yeah, I must review all the README.md...
