### ISSUE TITLE
TV with random smp fails next day if smp changes

### ISSUE THREAD

**Issue by rpcaeiro** [sermayoral/ha-samsungtv-encrypted#32]
Hi Sergio,
When you have some time, I would like to ask you if you could take a look at this problem. My TV HU8500 changes smp port each time I turn it on. Your integration, if I'm not mistaken, only scans the available uPNP ports when runs for the first time. If a TV like mine is turned on on the next day and if it uses other port on the next day, then the integration doesn't work anymore. A simple reboot of the HA solves the problem.
I have captured uPNP info and logs in debug mode. Attached you will find two files, one when the integration works and the other capture on the next day when it does not work because the integration can't connect to TV anymore.
[Samsung TV when all OK.docx](https://github.com/sermayoral/ha-samsungtv-encrypted/files/4606734/Samsung.TV.when.all.OK.docx)
[Samsung TV when not ok.docx](https://github.com/sermayoral/ha-samsungtv-encrypted/files/4606735/Samsung.TV.when.not.ok.docx)
Thanks
Rui

**Comment by sermayoral** [comment]
Hi @rpcaeiro.

What version of the custom are you using? HDMI-CEC version or normal one?

**Comment by sermayoral** [comment]
@rpcaeiro Assuming you are using the normal version of the custom component. Can you test the file attached?

[ha-samsungtv-encrypted-2.6.zip](https://github.com/sermayoral/ha-samsungtv-encrypted/files/4606822/ha-samsungtv-encrypted-2.6.zip)

I don't have your problem exactly, but the sourcelist does not refresh when i I add a new device until I reboot HA. This new version should fix both problems :-)

Test it well and let me know if it solves your problem in order to apply the update to the master branch

**Comment by rpcaeiro** [comment]
Thank you Sergio. Is installed! Allow me to test this for a few days.
You are fast :), really fast :) Amazing

**Comment by sermayoral** [comment]
@rpcaeiro of course, take the time you need :-)

**Comment by sermayoral** [comment]
@rpcaeiro any news?

**Comment by rpcaeiro** [comment]
Hi Sergio, after 3 days working, had no issues what so ever.
Thank you very much. Let’s close this one.
