### ISSUE TITLE
Broken in 0.113.2

### ISSUE THREAD

**Issue by luisiam** [sermayoral/ha-samsungtv-encrypted#50]
The component does not work anymore and I am getting the following error in HA.

```Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: 5:50:20 PM (1 occurrences)
Last logged: 5:50:20 PM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for samsungtv_encrypted doing I/O at custom_components/samsungtv_encrypted/PySmartCrypto/pysmartcrypto.py, line 95: websocket_response = requests.get(step4_url)
```

**Comment by sermayoral** [comment]
No error on my side. Does it still ocurr?

**Comment by luisiam** [comment]
Still none of the control works except adjusting volume. My TV is UN65H7150

**Comment by luisiam** [comment]
I figured out that I messed up with the configuration. Everything is working now.

**Comment by paulolesgaz** [comment]
Hello,

I've installed this integration in order to control my TV Samsung H6200. 
I'am a little bit new with HA, and I confess I took little time to figure out how to deal with this integration without the interface.

Anyway I managed to test the service with the development tools to power off my TV and it works. 

Also with automation.

But I have the same entry in my logs :

`2021-01-19 20:18:49 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for samsungtv_encrypted doing I/O at custom_components/samsungtv_encrypted/PySmartCrypto/pysmartcrypto.py, line 95: websocket_response = requests.get(step4_url)`

Even it's only a warning, I noticed, sometimes, ERRORs on other components just after. Don't know if this warning and the other errors are linked. But it could be usefull to take a look on this issue.

Anyway, at least with this integration I can shut down my tv and that is really great ! many thanks

( it is strange that poweron doesn't work :( , poweroff work, chup chdwn  work but not power on)

**Comment by edmund89** [comment]
Hi @paulolesgaz did you ever get the power on working? I have the same TV H6200.

Many Thanks

**Comment by paulolesgaz** [comment]
Hi @edmund89 ,

No, i wasn't able to make the power on work. Power off work, but not all the time. Finally I gave up.
