### ISSUE TITLE
55HU7500 buttons and off dont work

### ISSUE THREAD

**Issue by asiersan** [sermayoral/ha-samsungtv-encrypted#7]
In my 55HU7500, mute, vol+/- don't work. Volume bar, and Source select works ok.
Power off is not working too. I pulse it and status change to off but tv is on.
In few seconds the plugins detect that is on and returns status to on.

**Comment by sermayoral** [comment]
Mmm is strange, the HU7500 model is reported to work. 

Have you executed the get_token.py, introduce a 4-digit PIN on TV and store the ctx (tokken) and sessionid?

**Comment by asiersan** [comment]
Yes token is ok,
 and source change, and volume change by sliding bar is working. But power off and mute, volume buttons no.
The strange thing is the volume issue, in sliding bar is working, but buttons no.

**Comment by sermayoral** [comment]
Source, volume in sliding bar and getting volume and source status is done by uPNP, that is working for you.

Volume buttons, poweroff and mute is done by encrypted commands, and this is not working for you. 

Token and sessionid is used for encrypted commands. Maybe you have a wrong ctx due to copy paste, or something like that. If you use any other invented ctx in the configuration.yaml and restart Home Assistant, you will see that your media_player works in the same way

Could you repeat the get_token.py process? TV will show you another PIN. You will have another token and sessionid, put them in the configuration.yaml and restart Home Assistant.

**Comment by asiersan** [comment]
Solved. As you said. With new sesionid all ok
